version: "3"

services:
  postgres:
    container_name: tarjetasCredito_postgres
    image: postgres:16.1-alpine3.19
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
